name: Online Marketing NYC
favicon: null
layout_spectrum: 0.90334
typography_spectrum: 0.6432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f4ef'
    - '#151618'
    - '#5487b6'
    - '#5c5248'
    - '#96968e'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.6497776233591139
purpose: []
